CMAKE_DIRECTORY=CMake
CMAKE_MAKEFILE=${CMAKE_DIRECTORY}/Makefile
CMAKE_FILE_LISTS=${CMAKE_DIRECTORY}/CMakeLists.txt

main:${CMAKE_MAKEFILE}
	@${MAKE} -C "${CMAKE_DIRECTORY}";

${CMAKE_MAKEFILE}:${CMAKE_FILE_LISTS}
	cd "${CMAKE_DIRECTORY}" && cmake .;

.DEFAULT:${CMAKE_MAKEFILE}
	@${MAKE} -C "${CMAKE_DIRECTORY}" "$@";
