#ifndef GIT_H
#define GIT_H

#ifndef GIT_DIR_ENVIRONMENT
#define GIT_DIR_ENVIRONMENT "GIT_DIR"
#endif

#ifndef GIT_WORK_TREE_ENVIRONMENT
#define GIT_WORK_TREE_ENVIRONMENT "GIT_WORK_TREE"
#endif

#ifndef GIT_OBJECT_DIR_ENVIRONMENT
#define GIT_OBJECT_DIR_ENVIRONMENT "GIT_OBJECT_DIRECTORY"
#endif

#ifndef GIT_TEMPLATE_DIR_ENVIRONMENT
#define GIT_TEMPLATE_DIR_ENVIRONMENT "GIT_TEMPLATE_DIR"
#endif

#ifndef GIT_AUTHOR_NAME_ENVIRONMENT
#define GIT_AUTHOR_NAME_ENVIRONMENT "GIT_AUTHOR_NAME"
#endif

#ifndef GIT_AUTHOR_EMAIL_ENVIRONMENT
#define GIT_AUTHOR_EMAIL_ENVIRONMENT "GIT_AUTHOR_EMAIL"
#endif

#ifndef GIT_COMMITTER_NAME_ENVIRONMENT
#define GIT_COMMITTER_NAME_ENVIRONMENT "GIT_COMMITTER_NAME"
#endif

#ifndef GIT_COMMITTER_EMAIL_ENVIRONMENT
#define GIT_COMMITTER_EMAIL_ENVIRONMENT "GIT_COMMITTER_EMAIL"
#endif

#ifndef GIT_AUTHOR_DATE_ENVIRONMENT
#define GIT_AUTHOR_DATE_ENVIRONMENT "GIT_AUTHOR_DATE"
#endif

#ifndef GIT_COMMITTER_DATE_ENVIRONMENT
#define GIT_COMMITTER_DATE_ENVIRONMENT "GIT_COMMITTER_DATE"
#endif

void free_global_resources();

#endif
