#ifndef ENVIRONMENT_H
#define ENVIRONMENT_H

#define GIT_DIR_ENVIRONMENT "GIT_DIR"
#define GIT_WORK_TREE_ENVIRONMENT "GIT_WORK_TREE"
#define GIT_OBJECT_DIR_ENVIRONMENT "GIT_OBJECT_DIRECTORY"
#define GIT_CEILING_DIRECTORIES_ENVIRONMENT "GIT_CEILING_DIRECTORIES"
#define GIT_TEMPLATE_DIR_ENVIRONMENT "GIT_TEMPLATE_DIR"
#define GIT_AUTHOR_NAME_ENVIRONMENT "GIT_AUTHOR_NAME"
#define GIT_AUTHOR_EMAIL_ENVIRONMENT "GIT_AUTHOR_EMAIL"
#define GIT_COMMITTER_NAME_ENVIRONMENT "GIT_COMMITTER_NAME"
#define GIT_COMMITTER_EMAIL_ENVIRONMENT "GIT_COMMITTER_EMAIL"
#define GIT_AUTHOR_DATE_ENVIRONMENT "GIT_AUTHOR_DATE"
#define GIT_COMMITTER_DATE_ENVIRONMENT "GIT_COMMITTER_DATE"

#endif
